### ISSUE TITLE
how to use this ngx-waterfall ?

### ISSUE THREAD

**Issue by keandfan** [bsdfzzzy/ngx-waterfall#1]
as the title mentioned,can you give a detailed instruction or a detailed demo,thank you very much.
 

**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by bsdfzzzy** [comment]
You have three inputs: gap, itemWidth and shouldListenToResize. Gap means the gap width between the columns. ItemWidth means the width of each column. Their unit is px. And shouldListenToResize means if window:resize triggered, whether the waterfall component should be resized. Try them and welcome feedback. @keandfan

**Comment by keandfan** [comment]
I mean what should I do to import this module to my project, import { ngxwaterfallModule } from 'ngx-waterfall'?

**Comment by keandfan** [comment]
thank you for your response

**Comment by keandfan** [comment]
https://stackblitz.com/edit/angular-lqyvde?file=src%2Fapp%2Fapp.module.ts
i can't show the code as your demo,can you help me

**Comment by keandfan** [comment]
thank you for your response

**Comment by keandfan** [comment]
https://stackblitz.com/edit/angular-lqyvde?file=src%2Fapp%2Fapp.component.html
can you help me to solve the img load problem? if i use the imgloaded plug-in components ,the order will be out of order , can it order by the array order and not overlay? Look forward to your reply.

**Comment by keandfan** [comment]
![image](https://user-images.githubusercontent.com/37890226/54172327-ac7c2880-44b8-11e9-87ce-faa7f4598bdb.png)

and in my project your plug-in-component can'work, how can i deal with it

**Comment by bsdfzzzy** [comment]
Please check the demo code in /app/src. To fix the warning, check your Angular version first.
